### PR TITLE
Use less flashy colors.

### PR DESCRIPTION
**Pull request by Natim**
before 
after

### CODE REVIEW

**Comment by Natim** [comment]
@brassy- could we have your advice about this PR?

See https://mozilla.github.io/delivery-dashboard/dev/#pollbot/firefox/59.0a1

**Comment by brassy-** [comment]
I'll take a look during this week, cos I don't want to rush an answer. :)

**Comment by andymikulski** [comment]
_For reference, these styles are taken from the [Message Bars](https://design.firefox.com/photon/components/message-bars.html) page. The photon `Message Bars` are implemented via Ant's [Alert](https://ant.design/components/alert/) component._

I've actually had certain issues with the bright scheme myself while working on adding photon styles to [normandy](https://github.com/mozilla/normandy/). On pages where we have multiple Alerts, we found there were a lot of visually-competing elements, which became a little overwhelming.

One approach I had tried for a second was to add darkened borders, though that was mostly to distinguish them a bit better from buttons. I ended up taking them out in the most recent package to stay aligned with the actual written style guide, though. I've included some examples[0].

Not sure if any of this is helpful, but hopefully it shines some light on the context!

---

[0]

**Comment by Natim** [comment]
Ok I missed that so I guess photon-themes is already correct here.

**Comment by andymikulski** [comment]
I'd still be interested to hear @brassy- 's input on the matter. This has been an issue for a little bit, I'd love to have more discussion around it.

**Comment by Natim** [comment]
At least in the delivery-dashboard the color are hurting a little bit but maybe we are not supposed to use it like that.

**Pull request closed without merging**
